### ISSUE TITLE
ffmpegwriter

### ISSUE THREAD

**Issue by nafatrue** [ahoink/LiveBtcTracker#1]
hi i tried to write the output of your script with realtime values to an "mp4" file but no success is there any idea on how to do it

**Comment by ahoink** [comment]
There's no functionality implemented at the moment to export to an mp4. To do this you'd need to grab the plot figure each time it updates and write that to a frame of an mp4 using a file writer.

I don't have plans to add video exporting right now, but if you get it working you can submit a pull request
